cask_args appdir: '/Applications'

tap 'caskroom/versions'
tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'gcc'
brew 'git'
brew 'graphicsmagick'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'memcached'
brew 'mongodb'
brew 'mysql'
brew 'node'
brew 'openssl'
brew 'postgres'
brew 'redis'
brew 'spaceman-diff'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'