#!/usr/bin/env zsh

function usage() {
  cat << HEREDOC
profile

Usage: profile [--] <command>

Options:
  -h, --help                show this message
  -c, --count <iterations>  iterations to run [default: 10]
  -v, --verbose             print the profiled command's output

HEREDOC
}

function profile() {
  # initialize & parse any options received
  local -A options
  
  options=$(getopt -o "hc:v" -l "help,count:,verbose" -- "$@")
  eval set -- "$options"

  # initialize variables & values
  local -i count
  local -i verbose

  count=10
  verbose=0

  # process any passed options
  while true; do
    case "$1" in
      -h | --help ) usage; exit 1; ;;
      -c | --count ) count="$2"; shift 2 ;;
      -v | --verbose ) verbose=1; shift ;;
      -- ) shift; break ;;
      * ) break ;;
    esac
  done

  # profile the command
  for ((i = 0; i < count; i++)); do
    if ((verbose == 0)); then
      time "$@" &>/dev/null
    else
      time "$@"
    fi
  done
}

profile "$@"
