#!/bin/sh

set -eo pipefail

MEATBOX_USER=${MEATBOX_USER:-meatwallace}
MEATBOX_PASSWORD=${MEATBOX_PASSWORD:-meatword}

DOCKER_NAMESPACE=${DOCKER_USER:-meatwallace}
DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME:-meatbox}
DOCKER_IMAGE_VERSION=${DOCKER_IMAGE_VERSION:-development}
DOCKER_IMAGE_TAG_COMMIT="$DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION"
DOCKER_IMAGE_TAG_LATEST="$DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:latest"

echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin

docker build . \
  --build-arg "MEATBOX_USER=$MEATBOX_USER" \
  --build-arg "MEATBOX_PASSWORD=$MEATBOX_PASSWORD" \
  --build-arg "CACHE_BUSTER=$(date +%s)" \
  --tag "$DOCKER_IMAGE_TAG_COMMIT"
  
docker tag "$DOCKER_IMAGE_TAG_COMMIT" "$DOCKER_IMAGE_TAG_LATEST"

docker push "$DOCKER_IMAGE_TAG_COMMIT"
docker push "$DOCKER_IMAGE_TAG_LATEST"

